package model;

import model.base.BaseLesson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lesson extends BaseLesson<Lesson> {
	public static final Lesson dao = new Lesson().dao();
}

