package model;

import model.base.BaseOnlineuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Onlineuser extends BaseOnlineuser<Onlineuser> {
	public static final Onlineuser dao = new Onlineuser().dao();
}

