package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLesson<M extends BaseLesson<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setLessonname(java.lang.String lessonname) {
		set("lessonname", lessonname);
	}
	
	public java.lang.String getLessonname() {
		return getStr("lessonname");
	}
	
	public void setCapacity(java.lang.String capacity) {
		set("capacity", capacity);
	}
	
	public java.lang.String getCapacity() {
		return getStr("capacity");
	}
	
	public void setPeriod(java.lang.String period) {
		set("period", period);
	}
	
	public java.lang.String getPeriod() {
		return getStr("period");
	}
	
	public void setLessontime(java.lang.String lessontime) {
		set("lessontime", lessontime);
	}
	
	public java.lang.String getLessontime() {
		return getStr("lessontime");
	}
	
	public void setTeacher(java.lang.String teacher) {
		set("teacher", teacher);
	}
	
	public java.lang.String getTeacher() {
		return getStr("teacher");
	}
	
	public void setLessonplace(java.lang.String lessonplace) {
		set("lessonplace", lessonplace);
	}
	
	public java.lang.String getLessonplace() {
		return getStr("lessonplace");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	
}

